### ISSUE TITLE
Connect refused behind proxy

### ISSUE THREAD

**Issue by mikeshuangyan** [seanmiddleditch/gha-setup-ninja#5]
A connection error occurred when using this action behind a network proxy,
error log here:

```
Run seanmiddleditch/gha-setup-ninja@master
downloading https://github.com/ninja-build/ninja/releases/download/v1.10.0/ninja-win.zip
D:\github-runners\_work\_actions\seanmiddleditch\gha-setup-ninja\master\dist\index.js:310
    request.on('error', error => { throw error })
                                   ^

Error: connect ECONNREFUSED 52.216.30.68:443
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '52.216.30.68',
  port: 443
}
}
```

Thanks.

**Comment by seanmiddleditch** [comment]
This action downloads the ninja binaries from https://github.com/ninja-build/ninja/releases, and the binary download links apparently redirect to an AWS S3 bucket (the IP that failed for you is S3). I just double checked and even in a local browser I see the links redirect to an S3 URL, so that appears to be normal/expected behavior for github.

Can you confirm whether you have access to S3 behind your proxy? I'm quite ignorant of the specifics of proxies or whether any particular configuration would need to be done on gha-setup-ninja's end to handle the proxy properly, so if you do have access and something else needs to be done, I'll probably need a PR contributed to fix it.

**Comment by mikeshuangyan** [comment]
Thanks for your reply.

I tried with this command but not working.
Invoke-WebRequest -Uri "https://github.com/ninja-build/ninja/releases/latest/download/ninja-win.zip" -o "ninja-win.zip"

After set the proxy with this command, it works.
$Wcl = new-object System.Net.WebClient
$Wcl.Headers.Add("user-agent", "PowerShell Script")
$Wcl.Proxy.Credentials = [System.Net.CredentialCache]::DefaultNetworkCredentials
Invoke-WebRequest -Uri "https://github.com/ninja-build/ninja/releases/latest/download/ninja-win.zip" -o "ninja-win.zip"

**Comment by seanmiddleditch** [comment]
Hi @mikeshuangyan  - I pushed up a branch https://github.com/seanmiddleditch/gha-setup-ninja/tree/proxy that (hypothetically) adds proxy support via an `http_proxy` input variable.

I don't have a setup right now to actually _test_ this branch... I think I should figure out how to build a simple Docker container that requires a proxy so I can add a test to CI, but that's not something I'm likely to get to soon.

Would you be willing to check out if that branch lets you solve this problem? Further, let me know if the interface (a single `http_proxy` input variable) is ideal for you?
